import {StateGraph, StateSchema,START, END, type GraphNode, type CompiledStateGraph} from "@langchain/langgraph";
import z from "zod";
import { mistralAIModel , cohereModel, geminiModel } from "./model.ai.js";
import { createAgent , HumanMessage ,providerStrategy } from "langchain";


const state= new StateSchema({
    problem:z.string().default(""),
     solution_1:z.string().default(""),
     solution_2:z.string().default(""),
     judge:z.object({
        solution_1_score:z.number().default(0),
        solution_2_score:z.number().default(0),
        solution_1_reasoning:z.string().default(""),
        solution_2_reasoning:z.string().default(""),
     })
})

const solutionNode:GraphNode<typeof state> = async(state) => { //solution node is asking for state (not problem) because state k andar bohot saari cheezien hai-> problem, solution, reasoning and score lekin user ko sirf problem deni hai state->problem ie state k andr ki problem aur sab ai krega

    const [mistralResponse , cohereResponse] =await Promise.all([
        mistralAIModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }
}

const judgeNode:GraphNode<typeof state> = async(state) => {
    const {problem , solution_1, solution_2} = state;

    //judge response = {
    // solution_1_score: 0-10,
    // solution_2_score: 0-10,
    // solution_1_reasoning: string,
    // solution_2_reasoning: string
    //}} ie hame ek specific format mai response chahiye and uske liye ek agent create krna hota

    const judge= createAgent({
        model:geminiModel,
        responseFormat:providerStrategy(z.object({
            solution_1_score:z.number().min(0).max(10),
            solution_2_score:z.number().min(0).max(10),
            solution_1_reasoning:z.string().default(""),
            solution_2_reasoning:z.string().default("")
        })),
        systemPrompt:`You are a judge taskeed with evaluting two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
    })

    const judgeResponse = await judge.invoke({
        messages:[
            new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide score and reasoning.
                `)
        ]
    })

    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    } = judgeResponse.structuredResponse;

    return {
        judge:{
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }
}

//abhi nodes bani hai unko connecting edges ab banayenge

const graph = new StateGraph(state)
    .addNode("solution",solutionNode)
    .addNode("judge_node",judgeNode)
    .addEdge(START, "solution") 
    .addEdge("solution","judge_node") //solution node k output ko judge node k input se connect krna hai
    .addEdge("judge_node",END) //judge node k output ko end se connect krna hai

export default async function runGraph(problem: string): Promise<z.infer<typeof state>> {

    const app= graph.compile();

    const result = await app.invoke({
        problem: problem
    })

    return result;

}